# 计算设备

pytorch可以用来指定存储和计算的设备，如使用内存的cpu或使用显存的gpu。默认情况下，pytorch会将数据创建在内存，然后利用gpu计算。

查看gpu是否可用

In [1]:
import torch
from torch import nn

torch.cuda.is_available()

True

查看gpu数量

In [2]:
torch.cuda.device_count()

1

查看当前gpu索引号

In [3]:
torch.cuda.current_device()

0

根据索引号查看gpu名字

In [4]:
torch.cuda.get_device_name(0)

'GeForce RTX 2080'

# tensor的gpu计算

默认情况下，Tensor会被保存在内存上，因此每次打印Tensor的时候看不到任何gpu相关标识

In [5]:
x=torch.tensor([1,2,3])
x

tensor([1, 2, 3])

使用.cuda()可以将cpu上的Tensor转换（复制）到gpu上。如果有多块gpu，可以使用.cuda(i)来指定放在第i快gpu及相应的内存且cuda(0)和cudad()等价

In [6]:
x=x.cuda()
x

tensor([1, 2, 3], device='cuda:0')

可以通过tensor的device属性来查看tensor所在的设备

In [7]:
x.device

device(type='cuda', index=0)

可以直接在创建时指定设备

In [8]:
device=torch.device('cuda')
x=torch.tensor([1,2,3],device=device)
x

tensor([1, 2, 3], device='cuda:0')

In [9]:
x=torch.tensor([1,2,3]).to(device)
x

tensor([1, 2, 3], device='cuda:0')

如果对gpu上的数据进行运算，结果还是在gpu上

In [10]:
y=x**2
y

tensor([1, 4, 9], device='cuda:0')

存放在不同位置的数据不可以直接计算，位于不同gpu上的数据也不能直接进行计算

In [11]:
y+x.cpu()

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

# 模型的gpu计算

类似tensor，pytorch模型也可以通过.cuda转换到gpu上

In [12]:
nn=nn.Linear(3,1)
nn.parameters().__next__().device

device(type='cpu')

In [13]:
nn.cuda()
nn.parameters().__next__().device

device(type='cuda', index=0)

同样保证模型输入的Tensor和model在同一设备上