# 丢弃法(dropout)

深度学习模型常常使用丢弃法（dropout）来应对过拟合问题。

__从0实现__

In [ ]:
当对该隐藏层使用丢弃法时，该层的隐藏单元将有一定概率被丢弃掉。设丢弃概率为p，那么有p的概率hi​会被清零，有1−p的概率hi​会除以1−p做拉伸。

In [5]:
import torch
import torch.nn as nn 
import numpy as np 

def dropout(x,drop):
    x=x.float()
    assert 0<=drop<=1,'the drop must be 0-1'
    kp=1-drop
    if kp == 0:
        return torch.zeros_like(x)
    mask=(torch.randn(x.shape)<kp).float()
    return mask*x/kp

In [8]:
X = torch.arange(16).view(2, 8)
print(X)


tensor([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15]])


In [9]:
dropout(X, 0)

tensor([[ 0.,  1.,  2.,  0.,  4.,  5.,  0.,  7.],
        [ 8.,  9.,  0.,  0., 12., 13., 14., 15.]])

In [7]:
dropout(X, 0.5)

tensor([[ 0.,  2.,  4.,  6.,  8., 10., 12., 14.],
        [16., 18., 20.,  0., 24., 26.,  0., 30.]])

In [10]:
dropout(X, 1.0)

tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])

__简洁实现__

在PyTorch中，我们只需要在全连接层后添加Dropout层并指定丢弃概率。在训练模型时，Dropout层将以指定的丢弃概率随机丢弃上一层的输出元素；在测试模型时（即model.eval()后），Dropout层并不发挥作用。

In [16]:
numInput,numOutput,numHidden1,numHidden2=784,10,256,256
net=nn.Sequential(
    nn.Flatten(),
    nn.Linear(numInput,numHidden1),
    nn.ReLU(),
    nn.Dropout(0.5),
    nn.Linear(numHidden1,numHidden2),
    nn.ReLU(),
    nn.Dropout(0.5),
    nn.Linear(numHidden2,numOutput),
)